package com.froggylord.constellation.config;

public final class VisualConfig extends BaseConfigGroup {
    public boolean titleBackdrop = true;
    public boolean titleButtons = true;
    public boolean menuBackdrops = true;
    public boolean menuButtons = true;
    public boolean menuSliders = true;
    public boolean inGameMenuBackdrop = true;
    public boolean inGameMenuButtons = true;
    public boolean inGameMenuSliders = true;
    public boolean inGameMenuBlur = true;
    public boolean inGameMenuAccentRule = true;
    public int inGameMenuScrimColor = 0xFF080818;
    public int inGameMenuScrimOpacity = 176;
    public int inGameMenuAccentColor = 0xFFFFB830;
    public boolean playerInventoryTheme = true;
    public boolean playerInventoryModelFrame = true;
    public boolean playerInventorySlotFrames = true;
    public boolean basicContainerTheme = true;
    public boolean basicContainersOnHypixel = false;
    public boolean basicContainersInDungeons = false;
    public boolean basicContainerSlotFrames = true;
    public boolean craftingTableTheme = true;
    public boolean craftingTablesOnHypixel = false;
    public boolean craftingTableSlotFrames = true;
    public boolean craftingTableArrow = true;
    public boolean furnaceTheme = true;
    public boolean furnacesOnHypixel = false;
    public boolean furnaceSlotFrames = true;
    public boolean furnaceIndicatorBackplates = true;
    public boolean protectPuzzleContainers = true;
    public boolean protectMarketContainers = true;
    public int inventoryPanelColor = 0xF10E0E22;
    public int inventoryBorderColor = 0xFF36365E;
    public int inventoryAccentColor = 0xFFFFB830;
    public int inventorySlotColor = 0xE6080814;
    public int inventorySlotEdgeColor = 0xFF2A2A50;
    public int inventoryModelColor = 0xE6080814;
    public int inventoryLabelColor = 0xFFE8E6F8;
    public String containerTitleDenylist = "terminal;melody;harp;chronomatron;ultrasequencer;superpairs;fossil excavator;hacking;simon says";
    public boolean reducedMotion = false;
}
