package com.froggylord.constellation.constellation;

import com.froggylord.constellation.ConstellationClient;
import com.froggylord.constellation.config.HerculesConfig;
import com.froggylord.constellation.core.LocationManager.SkyblockArea;
import com.froggylord.constellation.core.StatStore;
import com.froggylord.constellation.data.TabList;
import com.froggylord.constellation.render.WorldRenderer;
import com.mojang.blaze3d.platform.InputConstants;
import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.arguments.IntegerArgumentType;
import com.mojang.brigadier.arguments.StringArgumentType;
import com.mojang.brigadier.builder.LiteralArgumentBuilder;
import com.mojang.brigadier.builder.RequiredArgumentBuilder;
import net.fabricmc.fabric.api.client.command.v2.FabricClientCommandSource;
import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents;
import net.fabricmc.fabric.api.client.message.v1.ClientReceiveMessageEvents;
import net.minecraft.client.KeyMapping;
import net.minecraft.client.Minecraft;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.ClickEvent;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.animal.chicken.Chicken;
import net.minecraft.world.entity.animal.cow.Cow;
import net.minecraft.world.entity.animal.equine.Horse;
import net.minecraft.world.entity.animal.pig.Pig;
import net.minecraft.world.entity.animal.rabbit.Rabbit;
import net.minecraft.world.entity.animal.sheep.Sheep;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;

import java.util.ArrayDeque;
import java.util.Arrays;
import java.util.Deque;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

// ported from SkyHanni (LGPL-3.0-or-later): features/misc/trevor/{TrevorFeatures,TrevorSolver,TrevorTracker,TalbotCircles,TrapperMobArea,TrevorMob}.kt
public final class HerculesTrevorHelper {
    private enum Area {OASIS("Oasis",new Vec3(126,77,-456)),GORGE("Mushroom Gorge",new Vec3(300,80,-509)),OVERGROWN("Overgrown Mushroom Cave",new Vec3(242,60,-389)),SETTLEMENT("Desert Settlement",new Vec3(184,86,-384)),GLOWING("Glowing Mushroom Cave",new Vec3(199,50,-512)),MOUNTAIN("Desert Mountain",new Vec3(255,148,-518)),FOUND("Found",Vec3.ZERO),NONE("Unknown",Vec3.ZERO);final String name;final Vec3 pos;Area(String name,Vec3 pos){this.name=name;this.pos=pos;}}
    private record Circle(Vec3 center,double radius){}
    private static final Pattern QUEST=Pattern.compile("^\\[NPC] Trevor: You can find your (?<rarity>.+) animal near the (?<location>.+)\\.$",Pattern.CASE_INSENSITIVE);
    private static final Pattern ABOVE=Pattern.compile("^The target is around (?<height>\\d+) blocks above, at a (?<angle>\\d+) degrees angle!$");
    private static final Pattern BELOW=Pattern.compile("^The target is around (?<height>\\d+) blocks below, at a (?<angle>\\d+) degrees angle!$");
    private static final Pattern KILL=Pattern.compile("^Killing the animal rewarded you (?<pelts>[\\d,]+) pelts\\.$",Pattern.CASE_INSENSITIVE);
    private static final Pattern SELF=Pattern.compile("^Your mob died randomly, you are rewarded (?<pelts>[\\d,]+) pelts\\.$",Pattern.CASE_INSENSITIVE);
    private static final Set<Integer> HEALTHS=Set.of(100,200,500,1000,2000,5000,10000,30000);
    private static final Map<String,String> RARITY_KEYS=Map.of("TRACKABLE","trackable","UNTRACKABLE","untrackable","UNDETECTED","undetected","ENDANGERED","endangered","ELUSIVE","elusive");
    private static final Deque<Integer> PELT_SECONDS=new ArrayDeque<>();private static final java.util.List<Circle> CIRCLES=new java.util.ArrayList<>();
    private static HerculesConfig cfg;private static KeyMapping key;private static Area area=Area.NONE;private static Vec3 target;private static String targetName="",rarity="",acceptCommand="";private static int candidate=-1,quietSeconds;private static boolean questActive,between,readyAlerted;private static long readyAt,acceptAt,lastHotkey;private static double estimatedHeight,minHeight,maxHeight;private static Object levelIdentity;
    private HerculesTrevorHelper(){}
    public static void init(HerculesConfig config){cfg=config;key=ConstellationClient.instance().keys().register("trevor",InputConstants.UNKNOWN.getValue());ClientReceiveMessageEvents.ALLOW_GAME.register((message,overlay)->{if(!overlay){capturePrompt(message);chat(clean(message.getString()));}return true;});ConstellationClient.tick().every(20,"hercules-trevor",HerculesTrevorHelper::second);ClientTickEvents.END_CLIENT_TICK.register(client->{while(key.consumeClick())hotkey(client);});}
    private static void capturePrompt(Component message){if(!active()||!clean(message.getString()).contains("Click an option: [YES] - [NO]"))return;acceptCommand="";for(Component part:message.toFlatList()){ClickEvent click=part.getStyle().getClickEvent();if(click instanceof ClickEvent.RunCommand run&&run.command().toUpperCase(Locale.ROOT).contains("YES")){acceptCommand=run.command();acceptAt=System.currentTimeMillis();break;}}}
    private static void chat(String line){if(!active())return;Matcher quest=QUEST.matcher(line);if(quest.matches()){start(quest.group("rarity"),quest.group("location"));return;}Matcher above=ABOVE.matcher(line),below=BELOW.matcher(line);if(above.matches()){talbot(Integer.parseInt(above.group("height")),Integer.parseInt(above.group("angle")));return;}if(below.matches()){talbot(-Integer.parseInt(below.group("height")),Integer.parseInt(below.group("angle")));return;}if(line.equals("You are at the exact height!")){Minecraft mc=Minecraft.getInstance();if(mc.player!=null)setHeight(mc.player.getY());return;}Matcher kill=KILL.matcher(line),self=SELF.matcher(line);if(kill.matches()){reward(kill,false);return;}if(self.matches()){reward(self,true);return;}if(line.equals("Return to the Trapper soon to get a new animal to hunt!")){ended(true);return;}if(line.equals("You ran out of time and the animal disappeared!"))ended(false);}
    private static void start(String foundRarity,String location){questActive=true;between=true;rarity=clean(foundRarity).toUpperCase(Locale.ROOT);area=area(location);target=null;targetName="";candidate=-1;estimatedHeight=minHeight=maxHeight=0;CIRCLES.clear();readyAt=System.currentTimeMillis()+Math.clamp(cfg.trevorReadySeconds,5,60)*1000L;readyAlerted=false;StatStore.add("trevor.quests",1);String key=RARITY_KEYS.get(rarity);if(key!=null)StatStore.add("trevor."+key,1);}
    private static void reward(Matcher matcher,boolean self){long pelts=parse(matcher.group("pelts"));StatStore.add("trevor.pelts",pelts);StatStore.add(self?"trevor.self":"trevor.killed",1);PELT_SECONDS.addLast((int)Math.min(Integer.MAX_VALUE,pelts));quietSeconds=0;}
    private static void ended(boolean died){questActive=false;area=Area.NONE;target=null;targetName="";candidate=-1;CIRCLES.clear();if(died&&cfg.trevorMobDiedAlert)alert("Mob died",cfg.trevorMobDiedTitle,cfg.trevorMobDiedChat,cfg.trevorMobDiedSound);}
    private static void second(){Minecraft mc=Minecraft.getInstance();if(mc.level!=levelIdentity){levelIdentity=mc.level;resetTransient();}if(!active()||mc.player==null||mc.level==null)return;readTab();if(questActive&&cfg.trevorSolver)findTarget(mc);if(!PELT_SECONDS.isEmpty()){PELT_SECONDS.addLast(0);if(++quietSeconds>Math.clamp(cfg.trevorTrackerIdleResetSeconds,30,600)){PELT_SECONDS.clear();quietSeconds=0;}while(PELT_SECONDS.size()>300)PELT_SECONDS.removeFirst();}if(!questActive&&between&&readyAt>0&&System.currentTimeMillis()>=readyAt&&!readyAlerted){readyAlerted=true;if(cfg.trevorReadyAlert)alert("Trapper ready",cfg.trevorReadyTitle,cfg.trevorReadyChat,cfg.trevorReadySound);}}
    private static void readTab(){boolean active=false;Area found=null;for(String raw:TabList.lines()){String line=clean(raw);if(line.startsWith("Time Left:"))active=true;if(line.startsWith("Location:"))found=area(line.substring(9).trim());else{Area direct=area(line);if(direct!=Area.NONE)found=direct;}}if(active){questActive=true;between=true;if(target==null&&found!=null)area=found;}else if(questActive){questActive=false;target=null;candidate=-1;}}
    private static void findTarget(Minecraft mc){Entity found=null;for(Entity e:mc.level.entitiesForRendering()){if(!(e instanceof LivingEntity living)||e==mc.player||!animal(e)||!e.isAlive())continue;String name=clean(e.getName().getString());boolean named=RARITY_KEYS.keySet().stream().anyMatch(r->name.toUpperCase(Locale.ROOT).startsWith(r+" "));int health=Math.round(living.getMaxHealth());if(!named&&!HEALTHS.contains(health))continue;if(candidate!=e.getId()){candidate=e.getId();return;}boolean oasisException=area==Area.OASIS&&(e instanceof Rabbit||e instanceof Sheep)&&!named;if(oasisException)return;double max=renderDistance(e);if(e.distanceToSqr(mc.player)>max*max||e.isInvisible()||!mc.player.hasLineOfSight(e))return;found=e;break;}if(found!=null){if(area!=Area.FOUND)alert("Saw "+mobName(found),true,false,false);area=Area.FOUND;target=found.position();targetName=mobName(found);}else if(candidate!=-1){candidate=-1;target=null;targetName="";}}
    private static boolean animal(Entity e){return e instanceof Cow||e instanceof Horse||e instanceof Sheep||e instanceof Pig||e instanceof Rabbit||e instanceof Chicken;}
    private static double renderDistance(Entity e){if(e instanceof Horse)return 90;if(e instanceof Rabbit)return 43;if(e instanceof Chicken)return 33;return 68;}
    private static String mobName(Entity e){if(e instanceof Cow)return"Cow";if(e instanceof Horse)return"Horse";if(e instanceof Sheep)return"Sheep";if(e instanceof Pig)return"Pig";if(e instanceof Rabbit)return"Rabbit";return"Chicken";}
    private static void talbot(int dy,int angle){Minecraft mc=Minecraft.getInstance();if(mc.player==null)return;setHeight(mc.player.getY()+dy);double radius=Math.tan(Math.toRadians(90-angle))*Math.abs(dy);if(radius>=0&&radius<=500)CIRCLES.add(new Circle(new Vec3(mc.player.getX(),mc.player.getY()+dy,mc.player.getZ()),radius));}
    private static void setHeight(double y){if(area==Area.NONE||area==Area.FOUND)return;double low=y-2.5,high=y+2.5;if(maxHeight==0){minHeight=low;maxHeight=high;}else if(high>=minHeight&&high<=maxHeight)maxHeight=high;else if(low>=minHeight&&low<=maxHeight)minHeight=low;else{minHeight=low;maxHeight=high;}estimatedHeight=(minHeight+maxHeight)/2;}
    public static void draw(WorldRenderer.Ctx ctx){if(!active())return;Minecraft mc=Minecraft.getInstance();if(mc.player==null)return;if(cfg.trevorTalbotCircles&&target==null)for(Circle c:CIRCLES)circle(ctx,c);Vec3 pos=target!=null?target:area.pos;if(target==null&&estimatedHeight!=0&&pos!=Vec3.ZERO)pos=new Vec3(pos.x,estimatedHeight,pos.z);if(pos==Vec3.ZERO||target==null&&!cfg.trevorAreaWaypoint||target!=null&&!cfg.trevorTargetWaypoint)return;double range=Math.clamp(cfg.trevorWaypointRange,32,1024);if(mc.player.position().distanceToSqr(pos)>range*range)return;int color=target!=null?cfg.trevorTargetColor:cfg.trevorAreaColor;String label=target!=null?(targetName.isBlank()?"Trevor target":targetName):area.name;if(cfg.trevorWaypointDistance)label+=" "+Math.round(mc.player.position().distanceTo(pos))+"m";if(cfg.trevorWaypointBox)ctx.highlight(new AABB(pos.x-.5,pos.y-.1,pos.z-.5,pos.x+.5,pos.y+1.5,pos.z+.5),color,cfg.trevorThroughWalls);if(cfg.trevorWaypointBeam)ctx.beam(pos.x,pos.y,pos.z,color,Math.clamp(cfg.trevorBeamHeight,2,64),cfg.trevorThroughWalls);if(cfg.trevorWaypointLine)ctx.line(mc.player.getEyePosition(),pos.add(0,.8,0),color,cfg.trevorThroughWalls);ctx.label(pos.add(0,1.8,0),label,color,cfg.trevorThroughWalls);}
    private static void circle(WorldRenderer.Ctx ctx,Circle c){int segments=Math.clamp(cfg.trevorCircleSegments,24,256);Vec3 prior=null;for(int i=0;i<=segments;i++){double a=Math.PI*2*i/segments;Vec3 point=new Vec3(c.center.x+Math.cos(a)*c.radius,c.center.y,c.center.z+Math.sin(a)*c.radius);if(prior!=null)ctx.line(prior,point,cfg.trevorCircleColor,cfg.trevorThroughWalls);prior=point;}}
    public static String hudText(){if(!active())return null;boolean showTracker=cfg.trevorTracker&&(questActive||cfg.trevorTrackerBetweenQuests&&between),showCooldown=cfg.trevorCooldownHud&&between;if(!showTracker&&!showCooldown)return null;Map<String,String> rows=new LinkedHashMap<>();rows.put("quests","Quests: "+StatStore.getLong("trevor.quests",0));rows.put("pelts","Pelts: "+StatStore.getLong("trevor.pelts",0));rows.put("rate","Pelts/hour: "+rate());rows.put("killed","Killed: "+StatStore.getLong("trevor.killed",0));rows.put("self","Self-killed: "+StatStore.getLong("trevor.self",0));for(String key:RARITY_KEYS.values())rows.put(key,title(key)+": "+StatStore.getLong("trevor."+key,0));StringBuilder out=new StringBuilder();if(showCooldown){long left=Math.max(0,readyAt-System.currentTimeMillis());append(out,questActive?"Active quest":left==0?"Trapper ready":"Ready in "+((left+999)/1000)+"s");}if(showTracker)for(String key:cfg.trevorTrackerOrder.split(",")){String row=rows.get(key.trim().toLowerCase(Locale.ROOT));if(row==null||key.trim().equalsIgnoreCase("rate")&&!cfg.trevorTrackerPeltsPerHour||RARITY_KEYS.containsValue(key.trim().toLowerCase(Locale.ROOT))&&!cfg.trevorTrackerRarities)continue;append(out,row);}return out.isEmpty()?null:out.toString();}
    private static int rate(){if(PELT_SECONDS.isEmpty())return 0;return(int)Math.round(PELT_SECONDS.stream().mapToInt(Integer::intValue).average().orElse(0)*3600);}
    private static void append(StringBuilder out,String value){if(!out.isEmpty())out.append(" | ");out.append(value);}
    private static String title(String key){return Character.toUpperCase(key.charAt(0))+key.substring(1);}
    private static void hotkey(Minecraft mc){if(!active()||mc.gui.screen()!=null||mc.getConnection()==null)return;long now=System.currentTimeMillis();if(now-lastHotkey<300)return;if(cfg.trevorAcceptHotkey&&!acceptCommand.isBlank()&&now-acceptAt>=200&&now-acceptAt<=5000){String command=acceptCommand.startsWith("/")?acceptCommand.substring(1):acceptCommand;mc.getConnection().sendCommand(command);acceptCommand="";lastHotkey=now;return;}if(cfg.trevorWarpHotkey){mc.getConnection().sendCommand("warp trapper");lastHotkey=now;}}
    public static void registerCommands(CommandDispatcher<FabricClientCommandSource> d){d.register(LiteralArgumentBuilder.<FabricClientCommandSource>literal("trevor").executes(c->status()).then(LiteralArgumentBuilder.<FabricClientCommandSource>literal("status").executes(c->status())).then(LiteralArgumentBuilder.<FabricClientCommandSource>literal("reset").executes(c->{resetAll();local("Trevor session reset.");return 1;})).then(LiteralArgumentBuilder.<FabricClientCommandSource>literal("clearcircles").executes(c->{CIRCLES.clear();return 1;})).then(LiteralArgumentBuilder.<FabricClientCommandSource>literal("test").then(RequiredArgumentBuilder.<FabricClientCommandSource,String>argument("state",StringArgumentType.word()).executes(c->test(StringArgumentType.getString(c,"state"))))).then(LiteralArgumentBuilder.<FabricClientCommandSource>literal("option").then(RequiredArgumentBuilder.<FabricClientCommandSource,String>argument("name",StringArgumentType.word()).then(RequiredArgumentBuilder.<FabricClientCommandSource,String>argument("state",StringArgumentType.word()).executes(c->option(StringArgumentType.getString(c,"name"),StringArgumentType.getString(c,"state")))))).then(LiteralArgumentBuilder.<FabricClientCommandSource>literal("number").then(RequiredArgumentBuilder.<FabricClientCommandSource,String>argument("name",StringArgumentType.word()).then(RequiredArgumentBuilder.<FabricClientCommandSource,Integer>argument("value",IntegerArgumentType.integer(1,1024)).executes(c->number(StringArgumentType.getString(c,"name"),IntegerArgumentType.getInteger(c,"value")))))));}
    private static int status(){local("Quest "+(questActive?"active":"inactive")+", area "+area.name+", target "+(target==null?"not found":targetName)+", "+StatStore.getLong("trevor.pelts",0)+" pelts tracked.");return 1;}
    private static int test(String state){switch(state.toLowerCase(Locale.ROOT)){case"quest"->start("ENDANGERED","Desert Mountain");case"above"->talbot(40,45);case"below"->talbot(-15,30);case"kill"->{Matcher m=KILL.matcher("Killing the animal rewarded you 5 pelts.");if(m.matches())reward(m,false);}case"died"->ended(true);case"ready"->{between=true;questActive=false;readyAt=System.currentTimeMillis();readyAlerted=false;}default->{local("Test must be quest, above, below, kill, died, or ready.");return 0;}}return status();}
    private static int option(String name,String raw){Boolean v=parseBool(raw);if(v==null){local("State must be on or off.");return 0;}switch(name.toLowerCase(Locale.ROOT)){case"solver"->cfg.trevorSolver=v;case"circles"->cfg.trevorTalbotCircles=v;case"tracker"->cfg.trevorTracker=v;case"cooldown"->cfg.trevorCooldownHud=v;case"ready"->cfg.trevorReadyAlert=v;case"death"->cfg.trevorMobDiedAlert=v;case"area"->cfg.trevorAreaWaypoint=v;case"target"->cfg.trevorTargetWaypoint=v;case"box"->cfg.trevorWaypointBox=v;case"beam"->cfg.trevorWaypointBeam=v;case"line"->cfg.trevorWaypointLine=v;case"walls"->cfg.trevorThroughWalls=v;case"warp"->cfg.trevorWarpHotkey=v;default->{local("Unknown option.");return 0;}}ConstellationClient.saveConfig();return status();}
    private static int number(String name,int value){switch(name.toLowerCase(Locale.ROOT)){case"ready"->cfg.trevorReadySeconds=value;case"range"->cfg.trevorWaypointRange=value;case"beam"->cfg.trevorBeamHeight=value;case"segments"->cfg.trevorCircleSegments=value;default->{local("Number must be ready, range, beam, or segments.");return 0;}}ConstellationClient.saveConfig();return status();}
    private static Area area(String value){String clean=clean(value);return Arrays.stream(Area.values()).filter(a->a!=Area.FOUND&&a!=Area.NONE&&a.name.equalsIgnoreCase(clean)).findFirst().orElse(Area.NONE);}
    private static void alert(String text,boolean title,boolean chat,boolean sound){Minecraft mc=Minecraft.getInstance();if(mc.player==null)return;if(title){mc.gui.hud.resetTitleTimes();mc.gui.hud.setTitle(Component.literal(text));}if(chat)local(text+".");if(sound)mc.player.playSound(SoundEvents.NOTE_BLOCK_PLING.value(),.8f,1f);}
    private static boolean active(){if(cfg==null||!cfg.enabled||!cfg.trevorHelper)return false;return !cfg.trevorRequireFarmingIslands||ConstellationClient.loc().area()==SkyblockArea.FARMING_ISLANDS;}
    private static void resetTransient(){area=Area.NONE;target=null;targetName="";candidate=-1;estimatedHeight=minHeight=maxHeight=0;questActive=false;between=false;readyAt=0;readyAlerted=false;acceptCommand="";acceptAt=0;CIRCLES.clear();}
    private static void resetAll(){resetTransient();between=false;readyAt=0;readyAlerted=false;PELT_SECONDS.clear();quietSeconds=0;}
    private static long parse(String value){try{return Long.parseLong(value.replace(",",""));}catch(Exception e){return 0;}}
    private static Boolean parseBool(String value){return switch(value.toLowerCase(Locale.ROOT)){case"on","true","yes","1"->true;case"off","false","no","0"->false;default->null;};}
    private static String clean(String value){return value.replaceAll("§[0-9A-FK-ORa-fk-or]","").trim();}
    private static void local(String text){Minecraft mc=Minecraft.getInstance();if(mc.player!=null)mc.player.sendSystemMessage(Component.literal("§2[Trevor] §f"+text));}
}
