package com.froggylord.constellation.constellation;

import com.froggylord.constellation.ConstellationClient;
import com.froggylord.constellation.config.HydraConfig;
import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.arguments.IntegerArgumentType;
import com.mojang.brigadier.arguments.StringArgumentType;
import com.mojang.brigadier.builder.LiteralArgumentBuilder;
import com.mojang.brigadier.builder.RequiredArgumentBuilder;
import net.fabricmc.fabric.api.client.command.v2.FabricClientCommandSource;
import net.fabricmc.fabric.api.client.message.v1.ClientReceiveMessageEvents;
import net.fabricmc.fabric.api.client.networking.v1.ClientPlayConnectionEvents;
import net.minecraft.ChatFormatting;
import net.minecraft.client.Minecraft;
import net.minecraft.network.chat.Component;
import net.minecraft.sounds.SoundEvents;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.function.Consumer;

// ported from Skyblocker (LGPL-3.0-or-later): skyblock/fishing/SeaCreature.java
// ported from Skyblocker (LGPL-3.0-or-later): skyblock/fishing/SeaCreatureTracker.java
// ported from SkyHanni (LGPL-3.0-or-later): features/fishing/tracker/SeaCreatureTracker.kt
// ported from Feesh (Apache-2.0): events/publishers/SeaCreaturesPublisher.kt
public final class HydraSeaCreatureTracker {
    public record Catch(String name,boolean doubleHook,long at) {}
    public record Creature(String name,String message,int rarity,String category) {}
    public record Entry(Creature creature,int amount,double percentage) {}
    public record Stats(List<Entry> entries,int total,int doubleHooks,long activeMillis,double perHour) {}
    private static final List<Creature> CREATURES=List.of(
        c("Squid","A Squid appeared.",0,"BASIC"),c("Sea Walker","You caught a Sea Walker.",0,"BASIC"),c("Sea Witch","It looks like you've disrupted the Sea Witch's brewing session. Watch out, she's furious!",1,"BASIC"),c("Sea Archer","You reeled in a Sea Archer.",1,"BASIC"),c("Rider of the Deep","The Rider of the Deep has emerged.",1,"BASIC"),c("Catfish","Huh? A Catfish!",2,"BASIC"),c("Sea Leech","Gross! A Sea Leech!",2,"BASIC"),c("Guardian Defender","You've discovered a Guardian Defender of the sea.",3,"BASIC"),c("Deep Sea Protector","You have awoken the Deep Sea Protector, prepare for a battle!",3,"BASIC"),c("Water Hydra","The Water Hydra has come to test your strength.",4,"BASIC"),
        c("Dumpster Diver","A Dumpster Diver has emerged from the swamp!",1,"BACKWATER_BAYOU"),c("Trash Gobbler","The Trash Gobbler is hungry for you!",0,"BACKWATER_BAYOU"),c("Banshee","The desolate wail of a Banshee breaks the silence.",2,"BACKWATER_BAYOU"),c("Bayou Sludge","A swampy mass of slime emerges, the Bayou Sludge!",3,"BACKWATER_BAYOU"),c("Alligator","A long snout breaks the surface of the water. It's an Alligator!",4,"BACKWATER_BAYOU"),c("Titanoboa","A massive Titanoboa surfaces. It's body stretches as far as the eye can see.",5,"BACKWATER_BAYOU"),
        c("Atoll Croaker","An inquisitive Atoll Croaker takes the bait!",0,"LOTUS_ATOLL"),c("Puddle Jumper","A Puddle Jumper is preparing for liftoff\u2014cast your rod into it and hold on tight!",4,"LOTUS_ATOLL"),c("Lotus Guardian","A Lotus Guardian emerges, ready to protect the Atoll.",1,"LOTUS_ATOLL"),c("gorF","What even is that?! A... gorF?",2,"LOTUS_ATOLL"),c("Frog Prince","Bow down before the Frog Prince... or pay the hefty price!",5,"LOTUS_ATOLL"),c("Drowned Captain","A Drowned Captain takes hold of your bobber!",3,"LOTUS_ATOLL"),
        c("Bogged","You've hooked a Bogged!",0,"GALATEA"),c("Wetwing","Look! A Wetwing emerges!",1,"GALATEA"),c("Tadgang","A gang of Liltads!",2,"GALATEA"),c("Ent","You've hooked an Ent, as ancient as the forest itself.",3,"GALATEA"),c("Stridersurfer","You caught a Stridersurfer.",2,"GALATEA"),c("The Loch Emperor","The Loch Emperor arises from the depths.",4,"GALATEA"),c("Nessie","You've caused a disturbance in the loch. Could it be... Nessie?",5,"GALATEA"),
        c("Fried Chicken","Smells of burning. Must be a Fried Chicken.",0,"CRIMSON_ISLE"),c("Volcanic Snail","You feel a burning sensation as you reel in a Volcanic Snail!",1,"CRIMSON_ISLE"),c("Fireproof Witch","Trouble's brewing, it's a Fireproof Witch!",2,"CRIMSON_ISLE"),c("Magma Slug","From beneath the lava appears a Magma Slug.",1,"CRIMSON_ISLE"),c("Moogma","You hear a faint Moo from the lava... A Moogma appears.",1,"CRIMSON_ISLE"),c("Lava Leech","A small but fearsome Lava Leech emerges.",2,"CRIMSON_ISLE"),c("Pyroclastic Worm","You feel the heat radiating as a Pyroclastic Worm surfaces.",2,"CRIMSON_ISLE"),c("Magma Pillar","A Magma Pillar rises from the lava.",3,"CRIMSON_ISLE"),c("Lava Flame","A Lava Flame flies out from beneath the lava.",2,"CRIMSON_ISLE"),c("Fire Eel","A Fire Eel slithers out from the depths.",2,"CRIMSON_ISLE"),c("Taurus","Taurus and his steed emerge.",3,"CRIMSON_ISLE"),c("Thunder","You hear a massive rumble as Thunder emerges.",5,"CRIMSON_ISLE"),c("Fiery Scuttler","A Fiery Scuttler inconspicuously waddles up to you, friends in tow.",4,"CRIMSON_ISLE"),c("Lord Jawbus","You have angered a legendary creature... Lord Jawbus has arrived.",5,"CRIMSON_ISLE"),c("Ragnarok","The sky darkens and the air thickens. The end times are upon us: Ragnarok is here.",5,"CRIMSON_ISLE"),
        c("Frosty","It's a snowman! He looks harmless.",0,"WINTER_ISLAND"),c("Frozen Steve","Frozen Steve fell into the pond long ago, never to resurface...until now!",0,"WINTER_ISLAND"),c("Grinch","The Grinch stole Jerry's Gifts...get them back!",1,"WINTER_ISLAND"),c("Yeti","What is this creature!?",4,"WINTER_ISLAND"),c("Nutcracker","You found a forgotten Nutcracker laying beneath the ice.",4,"WINTER_ISLAND"),c("Reindrake","A Reindrake forms from the depths.",4,"WINTER_ISLAND"),
        c("Jumpin' Jack","Watch out! It's Jumpin' Jack.",0,"SPOOKY"),c("Scarecrow","Phew! It's only a Scarecrow.",0,"SPOOKY"),c("Nightmare","You hear trotting from beneath the waves, you caught a Nightmare.",2,"SPOOKY"),c("Werewolf","It must be a full moon, a Werewolf appears.",3,"SPOOKY"),c("Phantom Fisher","The spirit of a long lost Phantom Fisher has come to haunt you.",4,"SPOOKY"),c("Grim Reaper","This can't be! The manifestation of death himself!",4,"SPOOKY"),
        c("Nurse Shark","A tiny fin emerges from the water, you've caught a Nurse Shark.",0,"SHARK"),c("Blue Shark","You spot a fin as blue as the water it came from, it's a Blue Shark.",1,"SHARK"),c("Tiger Shark","A striped beast bounds from the depths, the wild Tiger Shark!",3,"SHARK"),c("Great White Shark","Hide no longer, a Great White Shark has tracked your scent and thirsts for your blood!",4,"SHARK"),
        c("Frog Man","Is it a frog? Is it a man? Well, yes, sorta, IT'S FROG MAN!!!!!!",0,"HOTSPOT"),c("Inkling","You get an inkling that you've caught... an Inkling!",1,"HOTSPOT"),c("Snapping Turtle","A Snapping Turtle is coming your way, and it's ANGRY!",2,"HOTSPOT"),c("Blue Ringed Octopus","A garish set of tentacles arise. It's a Blue Ringed Octopus!",4,"HOTSPOT"),c("Wiki Tiki","The water bubbles and froths. A massive form emerges- you have disturbed the Wiki Tiki! You shall pay the price.",5,"HOTSPOT"),
        c("Small Mithril Grubber","A leech of the mines surfaces... you've caught a Mithril Grubber.",1,"SPECIAL"),c("Medium Mithril Grubber","A leech of the mines surfaces... you've caught a Medium Mithril Grubber.",1,"SPECIAL"),c("Large Mithril Grubber","A leech of the mines surfaces... you've caught a Large Mithril Grubber.",1,"SPECIAL"),c("Bloated Mithril Grubber","A leech of the mines surfaces... you've caught a Bloated Mithril Grubber.",1,"SPECIAL"),c("Oasis Sheep","An Oasis Sheep appears from the water.",1,"SPECIAL"),c("Oasis Rabbit","An Oasis Rabbit appears from the water.",1,"SPECIAL"),c("Carrot King","Is this even a fish? It's the Carrot King!",2,"SPECIAL"),c("Agarimoo","Your Chumcap Bucket trembles, it's an Agarimoo.",2,"SPECIAL"),c("Water Worm","A Water Worm surfaces!",2,"SPECIAL"),c("Poisoned Water Worm","A Poisoned Water Worm surfaces!",2,"SPECIAL"),c("Flaming Worm","A Flaming Worm surfaces from the depths!",2,"SPECIAL"),c("Lava Blaze","A Lava Blaze has surfaced from the depths!",3,"SPECIAL"),c("Lava Pigman","A Lava Pigman arose from the depths!",3,"SPECIAL"),c("Abyssal Miner","An Abyssal Miner breaks out of the water!",4,"SPECIAL"),c("Plhlegblast","WOAH! A Plhlegblast appeared.",5,"SPECIAL"));
    private static final Map<String,Creature> BY_MESSAGE=new HashMap<>();
    private static final Map<String,Integer> COUNTS=new HashMap<>();
    private static final List<Consumer<Catch>> CATCH_LISTENERS=new ArrayList<>();
    private static HydraConfig cfg;
    private static boolean doubleHook;
    private static long doubleHookAt;
    private static int total,doubleHooks;
    private static long activeMillis,lastTick,lastActivity;
    private static long lastCatchAt;
    private static String profileKey="";
    static {for(Creature c:CREATURES)BY_MESSAGE.put(c.message,c);}
    private HydraSeaCreatureTracker() {}
    public static void init(HydraConfig config){cfg=config;ConstellationClient.tick().every(20,"hydra-sea-creatures",HydraSeaCreatureTracker::tick);ClientReceiveMessageEvents.ALLOW_GAME.register((message,overlay)->overlay||onChat(clean(message.getString())));ClientPlayConnectionEvents.JOIN.register((a,b,c)->reset());ClientPlayConnectionEvents.DISCONNECT.register((a,b)->reset());}
    private static void tick(){long now=System.currentTimeMillis();String current=LyraStorageValue.currentProfileKey();if(current!=null&&!current.isBlank()&&!current.equals(profileKey)){if(!profileKey.isEmpty())resetSession();profileKey=current;}boolean tracker=active(),festival=HydraFishingFestival.trackingEnabled();if(!tracker&&!festival){lastTick=0;doubleHook=false;doubleHookAt=0;return;}if(doubleHook&&now-doubleHookAt>5000){doubleHook=false;doubleHookAt=0;}if(!tracker){lastTick=0;return;}Minecraft mc=Minecraft.getInstance();boolean fishing=mc.player!=null&&mc.player.fishing!=null;if(lastTick>0&&(fishing||now-lastActivity<=Math.max(10,cfg.seaCreatureTrackerPauseSeconds)*1000L))activeMillis+=Math.min(2000,now-lastTick);if(fishing)lastActivity=now;lastTick=now;}
    private static boolean onChat(String message){boolean tracker=active(),festival=HydraFishingFestival.trackingEnabled();if(!tracker&&!festival)return true;if(message.startsWith("It's a Double Hook!")){doubleHook=true;doubleHookAt=System.currentTimeMillis();return true;}Creature creature=BY_MESSAGE.get(message);if(creature==null)return true;boolean wasDouble=doubleHook;doubleHook=false;doubleHookAt=0;long now=System.currentTimeMillis();for(Consumer<Catch> listener:List.copyOf(CATCH_LISTENERS))listener.accept(new Catch(creature.name,wasDouble,now));if(!tracker)return true;int amount=wasDouble&&cfg.seaCreatureTrackerCountDouble?2:1;if(wasDouble)doubleHooks++;COUNTS.merge(creature.name,amount,Integer::sum);total+=amount;lastActivity=now;lastCatchAt=now;alert(creature);return !cfg.seaCreatureTrackerHideChat;}
    private static void alert(Creature creature){if(!cfg.seaCreatureAlerts||!cfg.rareSeaCreatureAlert||creature.rarity<Math.clamp(cfg.seaCreatureTrackerRareMinimum,0,5))return;Minecraft mc=Minecraft.getInstance();if(mc.player==null)return;if(cfg.seaCreatureTrackerRareTitle){mc.gui.hud.resetTitleTimes();mc.gui.hud.setTitle(Component.literal(creature.name+" caught").withColor(color(creature.rarity)&0xFFFFFF));}if(cfg.seaCreatureTrackerRareSound)mc.player.playSound(SoundEvents.ENDER_DRAGON_GROWL,0.6f,1.4f);if((cfg.seaCreatureTrackerRareParty||cfg.rareSeaCreaturePartyPing)&&mc.player.connection!=null)mc.player.connection.sendCommand("pc "+creature.name+" caught!");}
    public static Stats stats(){if(!active())return null;List<Entry> entries=new ArrayList<>();String category=cfg.seaCreatureTrackerCategory.toUpperCase(Locale.ROOT);int filteredTotal=0;for(Creature c:CREATURES)if(category.equals("ALL")||c.category.equals(category))filteredTotal+=COUNTS.getOrDefault(c.name,0);for(Creature c:CREATURES){int amount=COUNTS.getOrDefault(c.name,0);if(amount==0||!category.equals("ALL")&&!c.category.equals(category))continue;entries.add(new Entry(c,amount,filteredTotal==0?0:amount*100.0/filteredTotal));}Comparator<Entry> comparator=switch(cfg.seaCreatureTrackerSorting.toUpperCase(Locale.ROOT)){case"COUNT_ASC"->Comparator.comparingInt(Entry::amount);case"NAME"->Comparator.comparing(e->e.creature.name);case"RARITY_ASC"->Comparator.comparingInt(e->e.creature.rarity);case"RARITY_DESC"->Comparator.<Entry>comparingInt(e->e.creature.rarity).reversed().thenComparing(Comparator.comparingInt(Entry::amount).reversed());default->Comparator.comparingInt(Entry::amount).reversed();};entries.sort(comparator);if(entries.size()>Math.max(1,cfg.seaCreatureTrackerTop))entries=new ArrayList<>(entries.subList(0,Math.max(1,cfg.seaCreatureTrackerTop)));return new Stats(List.copyOf(entries),filteredTotal,doubleHooks,activeMillis,activeMillis<=0?0:filteredTotal*3_600_000.0/activeMillis);}
    public static boolean visible(){Minecraft mc=Minecraft.getInstance();return active()&&total>0&&(!cfg.seaCreatureTrackerOnlyWhileFishing||mc.player!=null&&(mc.player.fishing!=null||System.currentTimeMillis()-lastActivity<=Math.max(1,cfg.seaCreatureTrackerRecentSeconds)*1000L));}
    public static HydraConfig config(){return cfg;}
    public static long lastCatchAt(){return lastCatchAt;}
    private static int color(int rarity){return switch(rarity){case 0->cfg.seaCreatureTrackerCommonColor;case 1->cfg.seaCreatureTrackerUncommonColor;case 2->cfg.seaCreatureTrackerRareColor;case 3->cfg.seaCreatureTrackerEpicColor;case 4->cfg.seaCreatureTrackerLegendaryColor;default->cfg.seaCreatureTrackerMythicColor;};}
    public static int entryColor(Entry e){return color(e.creature.rarity);}
    public static List<String> knownCreatureNames(){return CREATURES.stream().map(Creature::name).toList();}
    public static void onCatch(Consumer<Catch> listener){if(listener!=null&&!CATCH_LISTENERS.contains(listener))CATCH_LISTENERS.add(listener);}
    private static boolean active(){return cfg!=null&&cfg.enabled&&cfg.seaCreatureTrackerSuite&&ConstellationClient.loc().onHypixel()&&ConstellationClient.loc().area()!=com.froggylord.constellation.core.LocationManager.SkyblockArea.KUUDRA;}
    private static Creature c(String name,String message,int rarity,String category){return new Creature(name,message,rarity,category);}
    private static String clean(String raw){String s=ChatFormatting.stripFormatting(raw);return s==null?"":s.trim();}
    private static void reset(){profileKey="";resetSession();}
    private static void resetSession(){COUNTS.clear();doubleHook=false;doubleHookAt=0;total=0;doubleHooks=0;activeMillis=0;lastTick=0;lastActivity=0;lastCatchAt=0;}
    public static void registerCommands(CommandDispatcher<FabricClientCommandSource> d){d.register(LiteralArgumentBuilder.<FabricClientCommandSource>literal("seacreatures").executes(c->status()).then(LiteralArgumentBuilder.<FabricClientCommandSource>literal("reset").executes(c->{resetSession();local("Sea creature session reset.");return 1;})).then(LiteralArgumentBuilder.<FabricClientCommandSource>literal("top").then(RequiredArgumentBuilder.<FabricClientCommandSource,Integer>argument("rows",IntegerArgumentType.integer(1,50)).executes(c->{cfg.seaCreatureTrackerTop=IntegerArgumentType.getInteger(c,"rows");save();return status();}))).then(LiteralArgumentBuilder.<FabricClientCommandSource>literal("category").then(RequiredArgumentBuilder.<FabricClientCommandSource,String>argument("name",StringArgumentType.word()).executes(c->category(StringArgumentType.getString(c,"name"))))).then(LiteralArgumentBuilder.<FabricClientCommandSource>literal("sort").then(RequiredArgumentBuilder.<FabricClientCommandSource,String>argument("mode",StringArgumentType.word()).executes(c->sort(StringArgumentType.getString(c,"mode"))))));}
    private static int status(){local("Tracked "+total+" sea creatures, "+doubleHooks+" double hooks, "+String.format(Locale.ROOT,"%.1f",stats()==null?0:stats().perHour)+" per hour.");return 1;}
    private static int category(String name){String value=name.toUpperCase(Locale.ROOT);if(!value.equals("ALL")&&CREATURES.stream().noneMatch(c->c.category.equals(value))){local("Unknown category. Use all, basic, backwater_bayou, lotus_atoll, galatea, crimson_isle, winter_island, spooky, shark, hotspot, or special.");return 0;}cfg.seaCreatureTrackerCategory=value;save();return status();}
    private static int sort(String mode){String value=mode.toUpperCase(Locale.ROOT);if(!List.of("COUNT_DESC","COUNT_ASC","RARITY_DESC","RARITY_ASC","NAME").contains(value)){local("Sort must be count_desc, count_asc, rarity_desc, rarity_asc, or name.");return 0;}cfg.seaCreatureTrackerSorting=value;save();return status();}
    private static void local(String text){Minecraft mc=Minecraft.getInstance();if(mc.player!=null)mc.player.sendSystemMessage(Component.literal("§3[Fishing] §f"+text));}
    private static void save(){ConstellationClient.saveConfig();}
}
