package com.froggylord.constellation.constellation;

import com.froggylord.constellation.config.HydraConfig;
import com.froggylord.constellation.core.BaseConstellation;
import com.froggylord.constellation.core.InitContext;
import com.froggylord.constellation.hud.HudManager;
import com.froggylord.constellation.hud.HudPosition;

public final class HydraFishing extends BaseConstellation {
    @Override public String id(){return"hydra";}
    @Override public String displayName(){return"Hydra";}
    @Override public String description(){return"fishing alerts and trackers";}
    @Override public void init(InitContext ctx){HydraConfig c=(HydraConfig)config;HydraSeaCreatureTracker.init(c);HydraFishingFestival.init(c);HydraPetLeveling.init(c);HydraThunderBottles.init(c);HydraFishingDeaths.init(c);HydraNessieDestination.init(c);HydraTrophyDiscoveries.init(c);HydraLootshare.init(c);HydraFishingProfitTracker.init(c);HydraFishingState.init(c);HydraFishingSafety.init(c);HydraGoldenFish.init(c);HydraWormholeFinder.init(c);HydraFishedItemNames.init(c);HydraRareFishingDrops.init(c);HydraBarnFishing.init(c);HydraHotspots.init(c);HydraDeployables.init(c);HydraConsumables.init(c);registerRenderer(HydraGoldenFish::draw);registerRenderer(HydraWormholeFinder::draw);registerRenderer(HydraFishedItemNames::draw);registerRenderer(HydraHotspots::draw);registerRenderer(HydraDeployables::draw);registerRenderer(HydraNessieDestination::draw);}
    @Override public void registerHud(HudManager hud){HydraConfig c=(HydraConfig)config;hud.register(new com.froggylord.constellation.hud.SeaCreatureTrackerHudWidget(HudPosition.of(2,82),()->c.enabled&&c.seaCreatureTrackerSuite&&c.seaCreatureTrackerHud));hud.register(new com.froggylord.constellation.hud.FishingFestivalHudWidget(HudPosition.of(2,88),()->c.enabled&&c.sharkCounter&&c.fishingFestivalSuite&&c.fishingFestivalHud));hud.register(new com.froggylord.constellation.hud.PetLevelHudWidget(HudPosition.of(2,94),()->c.enabled&&c.petLevelSuite&&c.petLevelHud));hud.register(new com.froggylord.constellation.hud.FishingProfitHudWidget(HudPosition.of(6,51),()->c.enabled&&c.fishingProfitTracker&&c.fishingProfitHud));hud.register(new com.froggylord.constellation.hud.FishingHookHudWidget(HudPosition.of(50,45),()->c.enabled&&c.fishingStateSuite&&c.fishingRodTimerHud&&c.fishingHookDisplay));hud.register(new com.froggylord.constellation.hud.FishingBaitHudWidget(HudPosition.of(26,49),()->c.enabled&&c.fishingStateSuite&&c.baitDisplay&&c.fishingBaitDisplay));hud.register(new com.froggylord.constellation.hud.GoldenFishHudWidget(HudPosition.of(50,80),()->c.enabled&&c.goldenFishTimer&&c.goldenFishSuite&&c.goldenFishHud));hud.register(new com.froggylord.constellation.hud.BarnFishingHudWidget(HudPosition.of(50,86),()->c.enabled&&c.barnTimer&&c.barnTimerSuite&&c.barnTimerHud));hud.register(new com.froggylord.constellation.hud.DeployablesHudWidget(HudPosition.of(76,80),()->c.enabled&&c.totemTimer&&c.deployableSuite&&c.deployableHud));hud.register(new com.froggylord.constellation.hud.ConsumablesHudWidget(HudPosition.of(76,86),()->c.enabled&&c.consumableSuite&&c.consumableHud));hud.register(new com.froggylord.constellation.hud.HudWidget("hydra-trophy-discovery","Discovery",HydraTrophyDiscoveries::hudText,HudPosition.of(76,92),()->c.enabled&&c.trophyDiscoverySuite&&c.trophyDiscoveryHud));hud.register(new com.froggylord.constellation.hud.HudWidget("hydra-lootshare","Lootshare",HydraLootshare::hudText,HudPosition.of(76,98),()->c.enabled&&c.lootshareSuite&&c.lootshareHud));}
    @Override public void registerCommands(com.mojang.brigadier.CommandDispatcher<net.fabricmc.fabric.api.client.command.v2.FabricClientCommandSource> dispatcher){HydraSeaCreatureTracker.registerCommands(dispatcher);HydraFishingFestival.registerCommands(dispatcher);HydraPetLeveling.registerCommands(dispatcher);HydraThunderBottles.registerCommands(dispatcher);HydraFishingDeaths.registerCommands(dispatcher);HydraNessieDestination.registerCommands(dispatcher);HydraTrophyDiscoveries.registerCommands(dispatcher);HydraLootshare.registerCommands(dispatcher);HydraFishingProfitTracker.registerCommands(dispatcher);HydraFishingState.registerCommands(dispatcher);HydraFishingSafety.registerCommands(dispatcher);HydraGoldenFish.registerCommands(dispatcher);HydraWormholeFinder.registerCommands(dispatcher);HydraFishedItemNames.registerCommands(dispatcher);HydraRareFishingDrops.registerCommands(dispatcher);HydraBarnFishing.registerCommands(dispatcher);HydraHotspots.registerCommands(dispatcher);HydraDeployables.registerCommands(dispatcher);HydraConsumables.registerCommands(dispatcher);}
}
